# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/v500/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/v500/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/lge/v500/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/lge/v500/proprietary/vendor/bin/mpdecision:system/vendor/bin/mpdecision \
    vendor/lge/v500/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/lge/v500/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/lge/v500/proprietary/vendor/bin/sensors.qcom:system/vendor/bin/sensors.qcom \
    vendor/lge/v500/proprietary/vendor/bin/thermald:system/vendor/bin/thermald \
    vendor/lge/v500/proprietary/vendor/lib/hw/camera.vendor.msm8960.so:system/vendor/lib/hw/camera.vendor.msm8960.so \
    vendor/lge/v500/proprietary/vendor/lib/hw/flp.msm8960.so:system/vendor/lib/hw/flp.msm8960.so \
    vendor/lge/v500/proprietary/vendor/lib/sensors.gpad83.so:system/vendor/lib/sensors.gpad83.so \
    vendor/lge/v500/proprietary/vendor/lib/libAKM.so:system/vendor/lib/libAKM.so \
    vendor/lge/v500/proprietary/vendor/lib/libHDR.so:system/vendor/lib/libHDR.so \
    vendor/lge/v500/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/lge/v500/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/lge/v500/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/lge/v500/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_imx119_default_video.so:system/vendor/lib/libchromatix_imx119_default_video.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_imx119_preview.so:system/vendor/lib/libchromatix_imx119_preview.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_imx119_vt.so:system/vendor/lib/libchromatix_imx119_vt.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_ov5693_default_video.so:system/vendor/lib/libchromatix_ov5693_default_video.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_ov5693_preview.so:system/vendor/lib/libchromatix_ov5693_preview.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_ov5693_zsl.so:system/vendor/lib/libchromatix_ov5693_zsl.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_s5k4e5ya_default_video.so:system/vendor/lib/libchromatix_s5k4e5ya_default_video.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_s5k4e5ya_preview.so:system/vendor/lib/libchromatix_s5k4e5ya_preview.so \
    vendor/lge/v500/proprietary/vendor/lib/libchromatix_s5k4e5ya_zsl.so:system/vendor/lib/libchromatix_s5k4e5ya_zsl.so \
    vendor/lge/v500/proprietary/vendor/lib/libcsd-client.so:system/vendor/lib/libcsd-client.so \
    vendor/lge/v500/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/lge/v500/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/lge/v500/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/lge/v500/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/lge/v500/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/lge/v500/proprietary/vendor/lib/libgemini.so:system/vendor/lib/libgemini.so \
    vendor/lge/v500/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/lge/v500/proprietary/vendor/lib/libimage-jpeg-enc-omx-comp.so:system/vendor/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/lge/v500/proprietary/vendor/lib/libimage-omx-common.so:system/vendor/lib/libimage-omx-common.so \
    vendor/lge/v500/proprietary/vendor/lib/libmercury.so:system/vendor/lib/libmercury.so \
    vendor/lge/v500/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_3a_legacy.so:system/vendor/lib/libmmcamera_3a_legacy.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_frameproc.so:system/vendor/lib/libmmcamera_frameproc.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_plugin.so:system/vendor/lib/libmmcamera_plugin.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_statsproc31.so:system/vendor/lib/libmmcamera_statsproc31.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_tintless_wrapper.so:system/vendor/lib/libmmcamera_tintless_wrapper.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmjpeg_interface.so:system/vendor/lib/libmmjpeg_interface.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmstillomx.so:system/vendor/lib/libmmstillomx.so \
    vendor/lge/v500/proprietary/vendor/lib/libmorpho_image_stab31.so:system/vendor/lib/libmorpho_image_stab31.so \
    vendor/lge/v500/proprietary/vendor/lib/libmorpho_movie_stabilization.so:system/vendor/lib/libmorpho_movie_stabilization.so \
    vendor/lge/v500/proprietary/vendor/lib/libmorpho_noise_reduction.so:system/vendor/lib/libmorpho_noise_reduction.so \
    vendor/lge/v500/proprietary/vendor/lib/libmorpho_video_denoiser.so:system/vendor/lib/libmorpho_video_denoiser.so \
    vendor/lge/v500/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/lge/v500/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/lge/v500/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/lge/v500/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/lge/v500/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/lge/v500/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/lge/v500/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/lge/v500/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/lge/v500/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/lge/v500/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/lge/v500/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/lge/v500/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/lge/v500/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/lge/v500/proprietary/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
    vendor/lge/v500/proprietary/vendor/firmware/a300_pfp.fw:system/vendor/firmware/a300_pfp.fw \
    vendor/lge/v500/proprietary/vendor/firmware/a300_pm4.fw:system/vendor/firmware/a300_pm4.fw \
    vendor/lge/v500/proprietary/vendor/firmware/dsps.b00:system/vendor/firmware/dsps.b00 \
    vendor/lge/v500/proprietary/vendor/firmware/dsps.b01:system/vendor/firmware/dsps.b01 \
    vendor/lge/v500/proprietary/vendor/firmware/dsps.b02:system/vendor/firmware/dsps.b02 \
    vendor/lge/v500/proprietary/vendor/firmware/dsps.b03:system/vendor/firmware/dsps.b03 \
    vendor/lge/v500/proprietary/vendor/firmware/dsps.b04:system/vendor/firmware/dsps.b04 \
    vendor/lge/v500/proprietary/vendor/firmware/dsps.b05:system/vendor/firmware/dsps.b05 \
    vendor/lge/v500/proprietary/vendor/firmware/dsps.mdt:system/vendor/firmware/dsps.mdt \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b00:system/vendor/firmware/gss.b00 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b01:system/vendor/firmware/gss.b01 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b02:system/vendor/firmware/gss.b02 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b03:system/vendor/firmware/gss.b03 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b04:system/vendor/firmware/gss.b04 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b05:system/vendor/firmware/gss.b05 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b06:system/vendor/firmware/gss.b06 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b07:system/vendor/firmware/gss.b07 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b08:system/vendor/firmware/gss.b08 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b09:system/vendor/firmware/gss.b09 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b10:system/vendor/firmware/gss.b10 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.b11:system/vendor/firmware/gss.b11 \
    vendor/lge/v500/proprietary/vendor/firmware/gss.mdt:system/vendor/firmware/gss.mdt \
    vendor/lge/v500/proprietary/vendor/firmware/q6.b00:system/vendor/firmware/q6.b00 \
    vendor/lge/v500/proprietary/vendor/firmware/q6.b01:system/vendor/firmware/q6.b01 \
    vendor/lge/v500/proprietary/vendor/firmware/q6.b03:system/vendor/firmware/q6.b03 \
    vendor/lge/v500/proprietary/vendor/firmware/q6.b04:system/vendor/firmware/q6.b04 \
    vendor/lge/v500/proprietary/vendor/firmware/q6.b05:system/vendor/firmware/q6.b05 \
    vendor/lge/v500/proprietary/vendor/firmware/q6.b06:system/vendor/firmware/q6.b06 \
    vendor/lge/v500/proprietary/vendor/firmware/q6.mdt:system/vendor/firmware/q6.mdt \
    vendor/lge/v500/proprietary/vendor/firmware/tzapps.b00:system/vendor/firmware/tzapps.b00 \
    vendor/lge/v500/proprietary/vendor/firmware/tzapps.b01:system/vendor/firmware/tzapps.b01 \
    vendor/lge/v500/proprietary/vendor/firmware/tzapps.b02:system/vendor/firmware/tzapps.b02 \
    vendor/lge/v500/proprietary/vendor/firmware/tzapps.b03:system/vendor/firmware/tzapps.b03 \
    vendor/lge/v500/proprietary/vendor/firmware/tzapps.mdt:system/vendor/firmware/tzapps.mdt \
    vendor/lge/v500/proprietary/vendor/firmware/vidc.b00:system/vendor/firmware/vidc.b00 \
    vendor/lge/v500/proprietary/vendor/firmware/vidc.b01:system/vendor/firmware/vidc.b01 \
    vendor/lge/v500/proprietary/vendor/firmware/vidc.b02:system/vendor/firmware/vidc.b02 \
    vendor/lge/v500/proprietary/vendor/firmware/vidc.b03:system/vendor/firmware/vidc.b03 \
    vendor/lge/v500/proprietary/vendor/firmware/vidc.mdt:system/vendor/firmware/vidc.mdt \
    vendor/lge/v500/proprietary/vendor/firmware/vidc_1080p.fw:system/vendor/firmware/vidc_1080p.fw \
    vendor/lge/v500/proprietary/vendor/firmware/vidcfw.elf:system/vendor/firmware/vidcfw.elf \
    vendor/lge/v500/proprietary/vendor/firmware/wcnss.b00:system/vendor/firmware/wcnss.b00 \
    vendor/lge/v500/proprietary/vendor/firmware/wcnss.b01:system/vendor/firmware/wcnss.b01 \
    vendor/lge/v500/proprietary/vendor/firmware/wcnss.b02:system/vendor/firmware/wcnss.b02 \
    vendor/lge/v500/proprietary/vendor/firmware/wcnss.b04:system/vendor/firmware/wcnss.b04 \
    vendor/lge/v500/proprietary/vendor/firmware/wcnss.b05:system/vendor/firmware/wcnss.b05 \
    vendor/lge/v500/proprietary/vendor/firmware/wcnss.b06:system/vendor/firmware/wcnss.b06 \
    vendor/lge/v500/proprietary/vendor/firmware/wcnss.mdt:system/vendor/firmware/wcnss.mdt \
    vendor/lge/v500/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/lge/v500/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/lge/v500/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lge/v500/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lge/v500/proprietary/vendor/lib/egl/libplayback_adreno.so:system/vendor/lib/egl/libplayback_adreno.so \
    vendor/lge/v500/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lge/v500/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/lge/v500/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/lge/v500/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/lge/v500/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/lge/v500/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/lge/v500/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/lge/v500/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/lge/v500/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/lge/v500/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/lge/v500/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/lge/v500/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/lge/v500/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/lge/v500/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/lge/v500/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/lge/v500/proprietary/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/lge/v500/proprietary/vendor/lib/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/lge/v500/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/lge/v500/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/lge/v500/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/lge/v500/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/lge/v500/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/lge/v500/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/lge/v500/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
